# Generated by Django 5.2.17 on 2026-08-07 23:45

import proyectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'línea de investigación',
                'verbose_name_plural': 'líneas de investigación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, unique=True, verbose_name='código')),
                ('linea', models.CharField(max_length=200, verbose_name='línea de investigación')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre del proyecto')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='estado')),
                ('pdf', models.FileField(blank=True, null=True, upload_to=proyectos.models.pdf_upload_path, verbose_name='memoria técnica (PDF)')),
                ('pdf_nombre_original', models.CharField(blank=True, max_length=255, verbose_name='nombre original del PDF')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
