# Generated by Django 5.2.17 on 2026-08-07 23:45

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('rol', models.CharField(choices=[('jefe', 'Jefe de Departamento de Investigación'), ('investigador', 'Investigador')], default='investigador', max_length=20, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilInvestigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, unique=True, verbose_name='clave de investigador')),
                ('area_participacion', models.CharField(max_length=200, verbose_name='área de participación')),
                ('division', models.CharField(choices=[('ID', 'Investigación y Desarrollo'), ('IT', 'Ingeniería y Tecnología'), ('CB', 'Ciencias Básicas'), ('CS', 'Ciencias de la Salud')], max_length=2, verbose_name='división')),
                ('linea_investigacion', models.CharField(max_length=200, verbose_name='línea de investigación')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=usuarios.models.avatar_upload_path, verbose_name='avatar')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de investigador',
                'verbose_name_plural': 'perfiles de investigadores',
            },
        ),
    ]
